-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT * PRICE) AS SALES FROM PRODUCT AS A
JOIN OFFLINE_SALE AS B
ON B.PRODUCT_ID = A.PRODUCT_ID
GROUP BY product_code
ORDER BY SALES DESC, PRODUCT_CODE ASC

# SELECT PRODUCT_CODE, SUM(SALES_AMOUNT*PRICE) AS SALES
# FROM PRODUCT LEFT JOIN OFFLINE_SALE USING(PRODUCT_ID)
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC, PRODUCT_CODE ASC;
