-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, (
    SELECT SUM(PRICE) FROM USED_GOODS_BOARD
    WHERE WRITER_ID = USER_ID AND STATUS = 'DONE'
) AS TOTAL_SALES FROM USED_GOODS_USER
WHERE USER_ID IN (
    SELECT WRITER_ID FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
ORDER BY TOTAL_SALES